import {getWordsAction, setWordsAction, selectWordAction} from './WordsAction';
import {
  selectTeamAction,
  addTeamAction,
  setAddTeamAction,
  getRemoveTeamAction,
  setRemoveTeamAction,
  changeTeamNameAction,
  addTeamMemberAction,
  selectTeamMemberAction,
  setAddTeamMemberAction,
  getRemoveTeamMemberAction,
  setRemoveTeamMemberAction,
  setTeamsAction,
  initTeams,
  updateTeamNameAction,
  updateTeamMemberNameAction,
  changeTeamMemberNameAction,
} from './TeamAction';
import {getSettingsAction, setSettingsAction} from './SettingAction';
import {setTeam1Action, setTeam2Action, setTurnAction} from './GameAction';

export {
  getWordsAction,
  setWordsAction,
  selectWordAction,
  selectTeamAction,
  addTeamAction,
  setAddTeamAction,
  getRemoveTeamAction,
  setRemoveTeamAction,
  changeTeamNameAction,
  addTeamMemberAction,
  selectTeamMemberAction,
  setAddTeamMemberAction,
  getRemoveTeamMemberAction,
  setRemoveTeamMemberAction,
  setTeamsAction,
  initTeams,
  updateTeamNameAction,
  updateTeamMemberNameAction,
  changeTeamMemberNameAction,
  getSettingsAction,
  setSettingsAction,
  setTeam1Action,
  setTeam2Action,
  setTurnAction,
};
