import {getSettingsAction, setSettingsAction} from './SettingAction';
import {
  selectTeamAction,
  addTeamAction,
  setAddTeamAction,
  getRemoveTeamAction,
  setRemoveTeamAction,
  changeTeamNameAction,
  addTeamMemberAction,
  selectTeamMemberAction,
  setAddTeamMemberAction,
  getRemoveTeamMemberAction,
  setRemoveTeamMemberAction,
  setTeamsAction,
  initTeams,
  updateTeamNameAction,
  setCheckAction,
  chooseTeamsAction,
  setCheckMemberAction,
  setOneTeamAction,
  getOneTeamAction,
} from './TeamAction';
import {
  setGameTeamsAction,
  setTurnsAction,
  setStartAction,
  setChangeStageAction,
  setNextTurnAction,
  chooseMembersAction,
  resetGameAction,
  selectWordAction,
  getWordsAction,
  setWordsAction,
  getCategoriesAction,
  setCategoriesAction,
  setGameAction,
  setDifficultyAction,
  setGoalAction,
  setNewWordsAction,
  getNewWordsAction,
  setNewTurnAction,
  gameOverAction,
  setCheckAnswersAction,
  setPointsAction,
  createGameAction,
} from './GameAction';
import {
  registerAction,
  loginAction,
  authSuccessAction,
  setErrorMessage,
} from './AuthAction';
import {
  setFriendsAction,
  setAddFriendAction,
  initFriends,
  addFriendAction,
} from './FriendAction';

export {
  selectTeamAction,
  addTeamAction,
  setAddTeamAction,
  getRemoveTeamAction,
  setRemoveTeamAction,
  changeTeamNameAction,
  addTeamMemberAction,
  selectTeamMemberAction,
  setAddTeamMemberAction,
  getRemoveTeamMemberAction,
  setRemoveTeamMemberAction,
  setTeamsAction,
  initTeams,
  updateTeamNameAction,
  setCheckAction,
  setCheckMemberAction,
  chooseTeamsAction,
  chooseMembersAction,
  getSettingsAction,
  setSettingsAction,
  setGameTeamsAction,
  setTurnsAction,
  setStartAction,
  setChangeStageAction,
  setNextTurnAction,
  resetGameAction,
  selectWordAction,
  getWordsAction,
  setWordsAction,
  getCategoriesAction,
  setCategoriesAction,
  setGameAction,
  setDifficultyAction,
  setGoalAction,
  setNewWordsAction,
  getNewWordsAction,
  setNewTurnAction,
  gameOverAction,
  registerAction,
  loginAction,
  authSuccessAction,
  setErrorMessage,
  setFriendsAction,
  setAddFriendAction,
  initFriends,
  addFriendAction,
  setOneTeamAction,
  getOneTeamAction,
  setCheckAnswersAction,
  setPointsAction,
  createGameAction,
};
