import {getWordsAction, setWordsAction} from './WordsAction';
import {
  selectTeamAction,
  addTeamAction,
  setAddTeamAction,
  getRemoveTeamAction,
  setRemoveTeamAction,
  changeTeamNameAction,
  addTeamMemberAction,
  selectTeamMemberAction,
  setAddTeamMemberAction,
  getRemoveTeamMemberAction,
  setRemoveTeamMemberAction,
  setTeamsAction,
  initTeams,
  updateTeamNameAction,
  updateTeamMemberNameAction,
  changeTeamMemberNameAction,
  setCheckAction,
  getCheckAction,
  chooseTeamsAction,
  chooseMembersAction,
  setCheckMemberAction,
  getCheckMemberAction,
} from './TeamAction';
import {getSettingsAction, setSettingsAction} from './SettingAction';
import {
  setGameTeamsAction,
  setTurnsAction,
  setTurnAction,
  setStartAction,
  setChangeStageAction,
  setNextTurnAction,
} from './GameAction';

export {
  getWordsAction,
  setWordsAction,
  selectTeamAction,
  addTeamAction,
  setAddTeamAction,
  getRemoveTeamAction,
  setRemoveTeamAction,
  changeTeamNameAction,
  addTeamMemberAction,
  selectTeamMemberAction,
  setAddTeamMemberAction,
  getRemoveTeamMemberAction,
  setRemoveTeamMemberAction,
  setTeamsAction,
  initTeams,
  updateTeamNameAction,
  updateTeamMemberNameAction,
  changeTeamMemberNameAction,
  setCheckAction,
  getCheckAction,
  setCheckMemberAction,
  getCheckMemberAction,
  chooseTeamsAction,
  chooseMembersAction,
  getSettingsAction,
  setSettingsAction,
  setGameTeamsAction,
  setTurnsAction,
  setTurnAction,
  setStartAction,
  setChangeStageAction,
  setNextTurnAction,
};
